name: Trigger Order Scheduler (Offset 1)

on:
  schedule:
    - cron: '1-59/5 * * * *' # Minute 1, 6, 11, etc.
  workflow_dispatch:

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Endpoint
        run: |
          echo "Triggering Subscription Processor (Offset 1)..."
          curl -X GET https://horeca-backend-six.vercel.app/api/cron/process-subscriptions || echo "Failed to trigger"
