name: Trigger Order Scheduler (Offset 3)

on:
  schedule:
    - cron: '3-59/5 * * * *' # Minute 3, 8, 13, etc.
  workflow_dispatch:

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Endpoint
        run: |
          echo "Triggering Subscription Processor (Offset 3)..."
          curl -X GET https://horeca-backend-six.vercel.app/api/cron/process-subscriptions || echo "Failed to trigger"
