name: Trigger Order Scheduler (Offset 2)

on:
  schedule:
    - cron: '2-59/5 * * * *' # Minute 2, 7, 12, etc.
  workflow_dispatch:

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Endpoint
        run: |
          echo "Triggering Subscription Processor (Offset 2)..."
          curl -X GET https://horeca-backend-six.vercel.app/api/cron/process-subscriptions || echo "Failed to trigger"
